Ascii from .txt
Zeroks77/dotNET-Global-Tools pull request #7
Opened 2018-10-08 14:49 UTC by Zeroks77

Jetzt kannst du Asciiart von einer .txt laden...
 #3

2018-10-08 15:05 UTC, paule96 requested changes

2018-10-08 15:05 UTC, paule96 commented on src/Program.cs
> +            return  System.IO.File.ReadAllText($@"C:\Develop\botsay\.NET-Global-Tools\AsciiArt\{asciisrc}");
Arbeite mal mit relativen Pfaden anstatt mit festen

2018-10-08 16:30 UTC, Zeroks77 commented on src/Program.cs
> +            return  System.IO.File.ReadAllText($@"C:\Develop\botsay\.NET-Global-Tools\AsciiArt\{asciisrc}");
Wenn es geändert wurde, so ?

2018-10-09 06:52 UTC, paule96 approved these changes

2018-10-09 06:53 UTC, merged